### ISSUE TITLE
Open Discussion. User experience to install the distribution

### ISSUE THREAD

**Issue by angelbarrera92** [sighupio/fury-distribution#1]
Hi team.

Please, take a look to this repository. It contains:

1. `Furyfile.yml` with static versions of core-modules that has to be installed on every Fury Cluster.
2. `kustomization.yaml` file with the features that has to be installed on every Fury Cluster.
3. An E2E pipeline test (smoke tests) that tests every module is Running in a vanilla Kubernetes Cluster (provided by the e2e-testing environment project).

The idea is to have both files versioned in a repository (could be this one, renaming it). Then tag the master branch with a new release (as we are doing with all OSS software). This release will be the "distribution" version (as pack of core modules).

So. Let's say we've got:

Furyfile.yml:

```yaml
versions:
  networking: v1.0.0
  monitoring: v1.3.0
  logging: v1.2.1
  ingress: v1.4.1
  dr: v1.2.0-rc3

bases:
  - name: networking/calico
  - name: monitoring/prometheus-operator
  - name: monitoring/prometheus-operated
  - name: monitoring/grafana
  - name: monitoring/goldpinger
  - name: monitoring/kubeadm-sm
  - name: monitoring/kube-state-metrics
  - name: monitoring/node-exporter
  - name: logging/elasticsearch-single
  - name: logging/cerebro
  - name: logging/curator
  - name: logging/fluentd
  - name: logging/kibana
  - name: ingress/cert-manager
  - name: ingress/nginx
  - name: ingress/forecastle
  - name: dr/velero
```

And kustomization.yaml

```yaml
bases:
  # Networking
  - ./vendor/katalog/networking/calico
  # Monitoring
  - ./vendor/katalog/monitoring/prometheus-operator
  - ./vendor/katalog/monitoring/prometheus-operated
  - ./vendor/katalog/monitoring/grafana
  - ./vendor/katalog/monitoring/goldpinger
  - ./vendor/katalog/monitoring/kubeadm-sm
  - ./vendor/katalog/monitoring/kube-state-metrics
  - ./vendor/katalog/monitoring/node-exporter
  # Logging
  - ./vendor/katalog/logging/elasticsearch-single
  - ./vendor/katalog/logging/cerebro
  - ./vendor/katalog/logging/curator
  - ./vendor/katalog/logging/fluentd
  - ./vendor/katalog/logging/kibana
  # Ingress
  - ./vendor/katalog/ingress/cert-manager
  - ./vendor/katalog/ingress/nginx
  - ./vendor/katalog/ingress/forecastle
  # DR
  - ./vendor/katalog/dr/velero/velero-prem
  - ./vendor/katalog/dr/velero/velero-restic
```

And pipeline passed (smoke test testing that everything is running).
We can create a `v1.0.0` tag to this repository. Meaning that a new Fury Distribution Release is available.

Ok.

# Hands ON!

**What should be the user/devops/operator/delivery-team-member experience?**

How someone can install this distribution?

Define the flow in the comments as proposal please.

Initial scenario: **I've got a GKE/AKS/Kind/K8S Vanilla cluster and i want to install Fury Distribution on it.**
