### ISSUE TITLE
Enhance module management and add monitoring on KFDDistribution

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-distribution#105]
While analyzing the current state of the distro provider together with @smerlos and @Deepzima , we found some additions that are nice to have:

On the distribution side, we have the need to enable or disable components, but instead of enabling and disabling the full module we want a simpler approach:

```yaml
modules:
  networking:
    type: none|calico|cilium|eks
    # calico with tigera should not require the cidr as an input
    cilium:
      podCidr:
      nodeNetmask:
  ingress:
    nginx: 
      type: none|single|dual
  monitoring:
    # cannot be disabled
  logging:
    type: none|opensearch-single|opensearch-triple|loki
  auth:
    provider:
      type: none|basicAuth|sso
  dr:
    type: none|on-premises|eks
  policy:
    type: none|gatekeeper
```

Let's explain:

* modules.networking.type: this field defines if we want to install the networking, by default as `none`. We need to also add the configurations for calico/cilium (only the cidrs I think are needed here, other stuff can be achieved with customPatches)
* ingress.nginx.type: this field can also be `none`. if set to none, we won't install the nginx batteries and also we should avoid the creation of the ingresses for the modules
* monitoring cannot be disabled
* logging.type: can be `none` . If it's none, we just skip the module entirely
* dr.type: this is important for the Distribution provider, because we can define which type of velero installation we want to have, by default, for the distro provider we will use `on-premises` (as a default on the template) but it can also be none or eks. With eks we expect to put by hand the values that are passed automatically by furyctl in the EKSCluster provider. With none, we will not install it.
* policy.type: can also be `none` . If it's none, we skip the apply of all the stuff from the policy/opa module (for now, at least)

PS: **This applies also to EKS**
