### ISSUE TITLE
Velero external endpoint not considered

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [sighupio/fury-distribution#220]
When enabling the DR module with an external endpoint configured, furyctl also installs a MinIO instance inside the kube-system namespace and still uses the default endpoints and credentials.

## Snippet
`furyctl.yaml`:
```yaml
...
      dr:
        type: on-premises
        velero:
          externalEndpoint:
            accessKeyId: REDACTED
            bucketName: velero
            endpoint: other.minio.instance:9000
            insecure: true
            secretAccessKey: REDACTED
...
```

**Comment by nutellinoit** [comment]
Which version are you using?

**Comment by FedericoAntoniazzi** [comment]
furyctl v0.28.0 and distribution v1.28.0

**Comment by Al-Pragliola** [comment]
you should set .velero.backend = "externalEndpoint" because the default value is "minio" if it's not set:

```
      dr:
        type: on-premises
        velero:
          backend: externalEndpoint
          externalEndpoint:
            accessKeyId: REDACTED
            bucketName: velero
            endpoint: other.minio.instance:9000
            insecure: true
            secretAccessKey: REDACTED
```

to improve the UX maybe we should add a validation to that field

**Comment by FedericoAntoniazzi** [comment]
Thank you @Al-Pragliola, I missed that field.
What to do in case of installing velero in a EKS cluster? Should we set `type: on-premises` if we only want to use the external endpoint?

**Comment by Al-Pragliola** [comment]
The schema for an EKSCluster is different, here's an example:

```
      dr:
        type: eks
        velero:
          eks:
            bucketName: example-velero
            region: eu-west-1
```
