### ISSUE TITLE
[Template/DR] Minio is not scheduled on infra nodes

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-distribution#221]
Minio's statefulset is missing the node selectors / affinity / tolerations to get scheduled on the infra nodes.

Here's a kustomize patch that can be used for the fix:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: kube-system
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/role
                operator: In
                values:
                - infra
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/role
        operator: Equal
        value: infra
```
