### ISSUE TITLE
when using gatekeeper, if kyverno whitelist is set the manifests template will contain also patch to kyverno

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-distribution#327]
**Describe the bug**
When using `spec.distribution.modules.policy.type: gatekeeper` , if `spec.distribution.modules.policy.kyverno.additionalExcludeNamespace` is set, the kustomize template will be generated with some patching to kyverno. This should not happen. The kustomize build will fail with accumulated errors.

**To Reproduce**
Set `furyctl.yaml` with:

```yaml
      policy:
        type: gatekeeper
        kyverno:
          additionalExcludedNamespaces: ["some-ns"]
```

**Expected behavior**
The generated template should not have any kyverno references

**Kubernetes (please complete the following information):**
 - Fury Distribution 1.30.0, all providers
