### ISSUE TITLE
On-prem: missing gangplank `trustedCAPath` field in the schema

### ISSUE THREAD

**Issue by stefanoghinelli** [sighupio/fury-distribution#345]
**Describe the bug**  
The schema is currently missing the `Spec.Distribution.Modules.Auth.OIDCKubernetesAuth.trustedCAPath` field for the OnPremises provider.

```yaml
        "trustedCAPath": {
          "type": "boolean",
          "description": "If true, a trustedCAPath will be defined"
        }
```

This issue could be temporarily mitigated using a distribution patch, but a permanent fix is needed.

**To Reproduce**  
1. Attempt to use the OnPremises provider with `trustedCAPath`.  
2. Observe that the field is not present in the schema.  

**Expected behavior**  
The schema should include the `trustedCAPath` field, allowing its configuration for the OnPremises provider.

**Screenshots**  
N/A

**Desktop (please complete the following information):**  
N/A 

**Kubernetes (please complete the following information):**  
N/A 

**Additional context**  
The template affected is located at: `./templates/distribution/manifests/auth/secrets/gangplank.yml.tpl`.
